apiVersion: v1
kind: Service
metadata:
  name: wallarm-ingress-controller
  namespace: wallarm-ingress
  labels:
    app.kubernetes.io/name: wallarm-ingress
    app.kubernetes.io/instance: wallarm-ingress
    app.kubernetes.io/component: controller
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerSourceRanges:
    - 65.132.246.78/32
    - 112.216.0.186/32
  selector:
    app.kubernetes.io/name: wallarm-ingress
    app.kubernetes.io/instance: wallarm-ingress
    app.kubernetes.io/component: controller
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
